language: ruby
rvm:
  - jruby-19mode
  - 2.0.0
  - 2.1.1
  - 2.2.4
  - 2.3.5
  - 2.4.1
notifications:
  email:
    - scott@railsnewbie.com
bundler_args: --without debug guard performance
services: mongodb
